name: WeChat MiniProgram Demo CI/CD

on:
  push:
    branches:
      - feat-ce
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Upload MiniProgram
        env:
          WX_PRIVATE_KEY: ${{ secrets.WX_PRIVATE_KEY }}
        run: |
          mkdir -p ./build
          echo "$WX_PRIVATE_KEY" > ./build/key
          node ./build/ci.js --skip-key-write
